import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/page'
import MainMovie from '@/components/main-movie/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <main className='container mx-auto'>
        <Header/>
        <MainMovie/>
        {children}
        </main>
      </body>
    </html>
  )
}
